run_txfDir|.\Scenarios
run_txfScen|example1.cls
run_txfoDSS|example1_DV.DSS
run_txaScenDesc|The default scenario contains Future Land Use, Base ANN Sea Level Rise, Historical Hydrology, SWP Full Table A, CVP Full Contract, D1641 regulation along with BO RPAs, Wheeling and Intertie.
spnRunStartMonth|Oct
spnRunStartYear|1921
spnRunEndMonth|Sep
spnRunEndYear|2003
run_rdbDet|true
run_rdbProb|false
run_rdbD1641|false
run_rdbBO|true
hyd_rdb2005|false
hyd_rdb2030|true
hyd_rdb1|false
hyd_rdb2|false
hyd_rdb3|true
hyd_rdb4|false
hyd_rdbHis|true
hyd_rdbMid|false
hyd_rdbEnd|false
btnDSS_Auto|true
btnDSS_Manual|false
hyd_DSS_SV|CL_FUTURE_BO_080911_SV.DSS
hyd_DSS_SV_F|2020D09E
hyd_DSS_Init|CL_INIT.dss
hyd_DSS_Init_F|INITIAL
hyd_ckb1|false
hyd_ckb2|false
hyd_ckb3|false
hyd_ckb4|false
hyd_ckb5|false
hyd_ckb6|false
hyd_ckb7|false
hyd_ckb8|false
hyd_ckb9|false
hyd_ckb10|false
hyd_ckb11|false
hyd_ckb12|false
dem_rdbCurSWP|false
dem_rdbFutSWP|true
dem_rdbUD1|false
demtxt1|1911.5
demtxt2|1189.4
demtxt3|1032.1
demtxt3a|0
dem_rdbFullCVP|true
dem_rdbUD2|false
demtxt4|1963.1
demtxt5|147.65
demtxt6|281.06
fac_ckb1|false
fac_ckb2|false
fac_ckb3|false
fac_ckb4|false
fac_ckb5|false
fac_ckb6|false
fac_ckb7|false
fac_ckb8|false
fac_ckb9|false
fac_ckb10|false
fac_txf1| 2000 
fac_txf2| 1000 
fac_txf3| 2000 
fac_txf4| 1000 
fac_txf5| 3000 
fac_txf6| 2000 
fac_txf7| 2300 
fac_rdb1|false
fac_rdb2|false
fac_rdb3|false
fac_txf8| 500 
fac_txf9| 250 
fac_txf10| 420 
fac_txf11| 350 
fac_txf12| 65 
fac_txf13| 100 
fac_txf15| 0.85 
fac_txf16| 0.04 
fac_txf17| 4 
fac_txf18| 0.65 
fac_txf19| 0.6 
fac_txf20| 15000 
fac_ckb11|false
fac_ckb12|true
fac_ckb34|true
fac_ckb35|true
fac_ckb36|true
fac_ckb37|true
fac_ckb13|false
fac_ckb33|false
fac_txf23| 3500 
fac_ckb14|false
fac_ckb15|false
fac_ckb16|false
fac_ckb17|true
fac_ckb18|true
fac_ckb19|true
fac_ckb20|false
fac_txf21| 3000 
fac_ckb21|false
fac_ckb22|false
fac_ckb23|false
fac_ckb38|true
fac_ckb24|true
fac_ckb25|true
fac_ckb26|false
fac_txf22| 300 
fac_ckb27|false
fac_ckb28|false
fac_ckb29|false
fac_ckb30|true
fac_ckb31|true
fac_ckb32|true
ckbReg3|true
ckbReg4|true
ckbReg5|false
ckbReg6|true
ckbReg7|true
ckbReg15|true
ckbReg8|true
ckbReg9|true
ckbReg11|true
ckbReg12|true
ckbReg13|true
ckbReg14|true
ckbRegbo1|true
ckbRegbo2|true
ckbRegbo3|true
ckbRegbo4|true
ckbRegbo5|true
ckbReg1|false
ckbReg2|false
ckbReg10|false
ckbReg16|false
reg_rdbD1641|true
reg_rdbUD|false
op_rdb6|true
op_rdb7|true
op_rdb8|true
op_rdb1|true
op_rdb2|false
op_rdb3|false
op_rdb4|false
op_rdb5|false
op_ckbSWP|false
op_ntfSWP|100
op_ckbCWP|false
op_ntfCWP1|50
op_ntfCWP2|1
DATATABLEMODELS
END DATATABLEMODELS
USERDEFINEDFLAGS
1|false
2|false
3|false
4|false
5|false
END USERDEFINEDFLAGS
